#CodeEmailMKT.Domain.Entity.Customer.dcm.yml
---
CodeEmailMKT\Domain\Entity\Customer:
    type: entity
    repositoryClass: CodeEmailMKT\Infrastructure\Persistence\Doctrine\Repository\CustomerRepository
    table: customers
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            lenght: 200
            nullable: true
        email:
            type: string
            lenght: 200