#CodeEmailMKT.Domain.Entity.Campaign.dcm.yml
---
CodeEmailMKT\Domain\Entity\Campaign:
    type: entity
    repositoryClass: CodeEmailMKT\Infrastructure\Persistence\Doctrine\Repository\CampaignRepository
    table: campaings
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string(200)
        subject:
            type: string(200)
        template:
            type: text
    manyToMany:
        tags:
            targetEntity: CodeEmailMKT\Domain\Entity\Tag
            mappedBy: campaigns